%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [y] = direct_form_lowpass25khz_fixpt(x,h0,h1,h2,h3,h4)
	fm = get_fimath();

	persistent h0_reg h1_reg h2_reg h3_reg h4_reg x_reg_1 x_reg_2 x_reg_3 x_reg_4 x_reg_5 x_reg_6 x_reg_7 x_reg_8 x_reg_9;
	if (isempty(x_reg_1))
		 	h0_reg=fi(0, 1, 14, 13, fm);
 	h1_reg=fi(0, 0, 14, 18, fm);
 	h2_reg=fi(0, 0, 14, 16, fm);
 	h3_reg=fi(0, 0, 14, 15, fm);
 	h4_reg=fi(0, 0, 14, 15, fm);
 x_reg_1 = fi(0, 1, 14, 12, fm); x_reg_2 = fi(0, 1, 14, 12, fm); x_reg_3 = fi(0, 1, 14, 12, fm); x_reg_4 = fi(0, 1, 14, 12, fm); x_reg_5 = fi(0, 1, 14, 12, fm); x_reg_6 = fi(0, 1, 14, 12, fm); x_reg_7 = fi(0, 1, 14, 12, fm); x_reg_8 = fi(0, 1, 14, 12, fm); x_reg_9 = fi(0, 1, 14, 12, fm);
	end

	[N1_mul] = fi(basic_mul(x,h0_reg), 1, 14, 20, fm);
	[N2_mul] = fi(basic_mul(x_reg_1,h1_reg), 1, 14, 17, fm);
	[N3_mul] = fi(basic_mul(x_reg_2,h2_reg), 1, 14, 15, fm);
	[N4_mul] = fi(basic_mul(x_reg_3,h3_reg), 1, 14, 14, fm);
	[N5_mul] = fi(basic_mul(x_reg_4,h4_reg), 1, 14, 14, fm);
	[N6_mul] = fi(basic_mul(x_reg_5,h4_reg), 1, 14, 14, fm);
	[N7_mul] = fi(basic_mul(x_reg_6,h3_reg), 1, 14, 14, fm);
	[N8_mul] = fi(basic_mul(x_reg_7,h2_reg), 1, 14, 15, fm);
	[N9_mul] = fi(basic_mul(x_reg_8,h1_reg), 1, 14, 17, fm);
	[N10_mul] = fi(basic_mul(x_reg_9,h0_reg), 1, 14, 20, fm);
	[N11_mul] = fi(basic_add(N1_mul,N2_mul), 1, 14, 17, fm);
	[N12_mul] = fi(basic_add(N3_mul,N11_mul), 1, 14, 15, fm);
	[N13_mul] = fi(basic_add(N4_mul,N12_mul), 1, 14, 14, fm);
	[N14_mul] = fi(basic_add(N5_mul,N13_mul), 1, 14, 14, fm);
	[N15_mul] = fi(basic_add(N6_mul,N14_mul), 1, 14, 14, fm);
	[N16_mul] = fi(basic_add(N7_mul,N15_mul), 1, 14, 14, fm);
	[N17_mul] = fi(basic_add(N8_mul,N16_mul), 1, 14, 14, fm);
	[N18_mul] = fi(basic_add(N9_mul,N17_mul), 1, 14, 14, fm);
	[N19_mul] = fi(basic_add(N10_mul,N18_mul), 1, 14, 14, fm);

	y = fi(N19_mul, 1, 14, 14, fm);

	x_reg_9(:) = x_reg_8;
	x_reg_8(:) = x_reg_7;
	x_reg_7(:) = x_reg_6;
	x_reg_6(:) = x_reg_5;
	x_reg_5(:) = x_reg_4;
	x_reg_4(:) = x_reg_3;
	x_reg_3(:) = x_reg_2;
	x_reg_2(:) = x_reg_1;
	x_reg_1(:) = x;
 	h0_reg(:)=h0;
 	h1_reg(:)=h1;
 	h2_reg(:)=h2;
 	h3_reg(:)=h3;
 	h4_reg(:)=h4;

end

function [out] = basic_mul(in1,in2)
    fm = get_fimath();

    out = fi(in1 * in2, 1, 14, 14, fm);
end

function [out] = basic_add(in1,in2)
    fm = get_fimath();

    out = fi(in1 + in2, 1, 14, 14, fm);
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
