%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function y = direct_form_lowpass25khz_wrapper_fixpt(x,h0,h1,h2,h3,h4)
    fm = get_fimath();
    x_in = fi( x, 1, 14, 12, fm );
    h0_in = fi( h0, 1, 14, 20, fm );
    h1_in = fi( h1, 0, 14, 18, fm );
    h2_in = fi( h2, 0, 14, 16, fm );
    h3_in = fi( h3, 0, 14, 15, fm );
    h4_in = fi( h4, 0, 14, 15, fm );
    [y_out] = direct_form_lowpass25khz_fixpt( x_in, h0_in, h1_in, h2_in, h3_in, h4_in );
    y = double( y_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
