-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Yunus\Desktop\Bitirme\Matlab_Codes\codegen\direct_form_lowpass25khz\hdlsrc\direct_form_lowpass25khz_fixpt.vhd
-- Created: 2023-03-27 18:54:15
-- 
-- Generated by MATLAB 9.12, MATLAB Coder 5.4 and HDL Coder 3.20
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y                             ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: direct_form_lowpass25khz_fixpt
-- Source Path: direct_form_lowpass25khz_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY direct_form_lowpass25khz_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        x                                 :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En12
        h0                                :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En20
        h1                                :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En18
        h2                                :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En16
        h3                                :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En15
        h4                                :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En15
        ce_out                            :   OUT   std_logic;
        y                                 :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En14
        );
END direct_form_lowpass25khz_fixpt;


ARCHITECTURE rtl OF direct_form_lowpass25khz_fixpt IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL x_signed                         : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_1                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_2                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_3                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_4                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_5                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_6                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_7                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_8                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL x_reg_9                          : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL h0_signed                        : signed(13 DOWNTO 0);  -- sfix14_En20
  SIGNAL tmp                              : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL h0_reg                           : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL h1_unsigned                      : unsigned(13 DOWNTO 0);  -- ufix14_En18
  SIGNAL h1_reg                           : unsigned(13 DOWNTO 0);  -- ufix14_En18
  SIGNAL h2_unsigned                      : unsigned(13 DOWNTO 0);  -- ufix14_En16
  SIGNAL h2_reg                           : unsigned(13 DOWNTO 0);  -- ufix14_En16
  SIGNAL h3_unsigned                      : unsigned(13 DOWNTO 0);  -- ufix14_En15
  SIGNAL h3_reg                           : unsigned(13 DOWNTO 0);  -- ufix14_En15
  SIGNAL h4_unsigned                      : unsigned(13 DOWNTO 0);  -- ufix14_En15
  SIGNAL h4_reg                           : unsigned(13 DOWNTO 0);  -- ufix14_En15
  SIGNAL N1_mul                           : signed(13 DOWNTO 0);  -- sfix14_En20
  SIGNAL p16N1_mul_mul_temp               : signed(27 DOWNTO 0);  -- sfix28_En25
  SIGNAL p16N1_mul_cast                   : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N10_mul                          : signed(13 DOWNTO 0);  -- sfix14_En20
  SIGNAL p43N10_mul_mul_temp              : signed(27 DOWNTO 0);  -- sfix28_En25
  SIGNAL p43N10_mul_cast                  : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N9_mul                           : signed(13 DOWNTO 0);  -- sfix14_En17
  SIGNAL p40N9_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En18
  SIGNAL p40N9_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En30
  SIGNAL p40N9_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En30
  SIGNAL p40N9_mul_cast_2                 : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N8_mul                           : signed(13 DOWNTO 0);  -- sfix14_En15
  SIGNAL p37N8_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En16
  SIGNAL p37N8_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En28
  SIGNAL p37N8_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En28
  SIGNAL p37N8_mul_cast_2                 : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N7_mul                           : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p34N7_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En15
  SIGNAL p34N7_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En27
  SIGNAL p34N7_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En27
  SIGNAL N6_mul                           : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p31N6_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En15
  SIGNAL p31N6_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En27
  SIGNAL p31N6_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En27
  SIGNAL N5_mul                           : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p28N5_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En15
  SIGNAL p28N5_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En27
  SIGNAL p28N5_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En27
  SIGNAL N4_mul                           : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p25N4_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En15
  SIGNAL p25N4_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En27
  SIGNAL p25N4_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En27
  SIGNAL N3_mul                           : signed(13 DOWNTO 0);  -- sfix14_En15
  SIGNAL p22N3_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En16
  SIGNAL p22N3_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En28
  SIGNAL p22N3_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En28
  SIGNAL p22N3_mul_cast_2                 : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N2_mul                           : signed(13 DOWNTO 0);  -- sfix14_En17
  SIGNAL p19N2_mul_cast                   : signed(14 DOWNTO 0);  -- sfix15_En18
  SIGNAL p19N2_mul_mul_temp               : signed(28 DOWNTO 0);  -- sfix29_En30
  SIGNAL p19N2_mul_cast_1                 : signed(27 DOWNTO 0);  -- sfix28_En30
  SIGNAL p19N2_mul_cast_2                 : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N11_mul                          : signed(13 DOWNTO 0);  -- sfix14_En17
  SIGNAL p44N11_mul_add_cast              : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL p44N11_mul_add_cast_1            : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL p44N11_mul_add_temp              : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL p44N11_mul_cast                  : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N12_mul                          : signed(13 DOWNTO 0);  -- sfix14_En15
  SIGNAL p45N12_mul_add_cast              : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL p45N12_mul_add_cast_1            : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL p45N12_mul_add_temp              : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL p45N12_mul_cast                  : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N13_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p46N13_mul_add_cast              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL p46N13_mul_add_cast_1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL p46N13_mul_add_temp              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL N14_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N15_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N16_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL N17_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p50N17_mul_add_cast              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL p50N17_mul_add_cast_1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL p50N17_mul_add_temp              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL N18_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p51N18_mul_add_cast              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL p51N18_mul_add_cast_1            : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL p51N18_mul_add_temp              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL N19_mul                          : signed(13 DOWNTO 0);  -- sfix14_En14
  SIGNAL p52N19_mul_add_cast              : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL p52N19_mul_add_cast_1            : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL p52N19_mul_add_temp              : signed(20 DOWNTO 0);  -- sfix21_En20

BEGIN
  -- HDL code generation from MATLAB function: direct_form_lowpass25khz_fixpt
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- 
  --                                                                          %
  -- 
  --          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
  -- 
  --                                                                          %
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  x_signed <= signed(x);

  enb <= clk_enable;

  x_reg_1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_1 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_1 <= x_signed;
      END IF;
    END IF;
  END PROCESS x_reg_1_reg_process;


  x_reg_2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_2 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_2 <= x_reg_1;
      END IF;
    END IF;
  END PROCESS x_reg_2_reg_process;


  x_reg_3_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_3 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_3 <= x_reg_2;
      END IF;
    END IF;
  END PROCESS x_reg_3_reg_process;


  x_reg_4_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_4 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_4 <= x_reg_3;
      END IF;
    END IF;
  END PROCESS x_reg_4_reg_process;


  x_reg_5_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_5 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_5 <= x_reg_4;
      END IF;
    END IF;
  END PROCESS x_reg_5_reg_process;


  x_reg_6_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_6 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_6 <= x_reg_5;
      END IF;
    END IF;
  END PROCESS x_reg_6_reg_process;


  x_reg_7_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_7 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_7 <= x_reg_6;
      END IF;
    END IF;
  END PROCESS x_reg_7_reg_process;


  x_reg_8_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_8 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_8 <= x_reg_7;
      END IF;
    END IF;
  END PROCESS x_reg_8_reg_process;


  x_reg_9_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_reg_9 <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_reg_9 <= x_reg_8;
      END IF;
    END IF;
  END PROCESS x_reg_9_reg_process;


  h0_signed <= signed(h0);

  tmp <= resize(h0_signed(13 DOWNTO 7), 14);

  h0_reg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      h0_reg <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        h0_reg <= tmp;
      END IF;
    END IF;
  END PROCESS h0_reg_reg_process;


  h1_unsigned <= unsigned(h1);

  h1_reg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      h1_reg <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        h1_reg <= h1_unsigned;
      END IF;
    END IF;
  END PROCESS h1_reg_reg_process;


  h2_unsigned <= unsigned(h2);

  h2_reg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      h2_reg <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        h2_reg <= h2_unsigned;
      END IF;
    END IF;
  END PROCESS h2_reg_reg_process;


  h3_unsigned <= unsigned(h3);

  h3_reg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      h3_reg <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        h3_reg <= h3_unsigned;
      END IF;
    END IF;
  END PROCESS h3_reg_reg_process;


  h4_unsigned <= unsigned(h4);

  h4_reg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      h4_reg <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        h4_reg <= h4_unsigned;
      END IF;
    END IF;
  END PROCESS h4_reg_reg_process;


  p16N1_mul_mul_temp <= x_signed * h0_reg;
  p16N1_mul_cast <= p16N1_mul_mul_temp(24 DOWNTO 11);
  N1_mul <= p16N1_mul_cast(7 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0';

  p43N10_mul_mul_temp <= x_reg_9 * h0_reg;
  p43N10_mul_cast <= p43N10_mul_mul_temp(24 DOWNTO 11);
  N10_mul <= p43N10_mul_cast(7 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0';

  p40N9_mul_cast <= signed(resize(h1_reg, 15));
  p40N9_mul_mul_temp <= x_reg_8 * p40N9_mul_cast;
  p40N9_mul_cast_1 <= p40N9_mul_mul_temp(27 DOWNTO 0);
  p40N9_mul_cast_2 <= resize(p40N9_mul_cast_1(27 DOWNTO 16), 14);
  N9_mul <= p40N9_mul_cast_2(10 DOWNTO 0) & '0' & '0' & '0';

  p37N8_mul_cast <= signed(resize(h2_reg, 15));
  p37N8_mul_mul_temp <= x_reg_7 * p37N8_mul_cast;
  p37N8_mul_cast_1 <= p37N8_mul_mul_temp(27 DOWNTO 0);
  p37N8_mul_cast_2 <= p37N8_mul_cast_1(27 DOWNTO 14);
  N8_mul <= p37N8_mul_cast_2(12 DOWNTO 0) & '0';

  p34N7_mul_cast <= signed(resize(h3_reg, 15));
  p34N7_mul_mul_temp <= x_reg_6 * p34N7_mul_cast;
  p34N7_mul_cast_1 <= p34N7_mul_mul_temp(27 DOWNTO 0);
  N7_mul <= p34N7_mul_cast_1(26 DOWNTO 13);

  p31N6_mul_cast <= signed(resize(h4_reg, 15));
  p31N6_mul_mul_temp <= x_reg_5 * p31N6_mul_cast;
  p31N6_mul_cast_1 <= p31N6_mul_mul_temp(27 DOWNTO 0);
  N6_mul <= p31N6_mul_cast_1(26 DOWNTO 13);

  p28N5_mul_cast <= signed(resize(h4_reg, 15));
  p28N5_mul_mul_temp <= x_reg_4 * p28N5_mul_cast;
  p28N5_mul_cast_1 <= p28N5_mul_mul_temp(27 DOWNTO 0);
  N5_mul <= p28N5_mul_cast_1(26 DOWNTO 13);

  p25N4_mul_cast <= signed(resize(h3_reg, 15));
  p25N4_mul_mul_temp <= x_reg_3 * p25N4_mul_cast;
  p25N4_mul_cast_1 <= p25N4_mul_mul_temp(27 DOWNTO 0);
  N4_mul <= p25N4_mul_cast_1(26 DOWNTO 13);

  p22N3_mul_cast <= signed(resize(h2_reg, 15));
  p22N3_mul_mul_temp <= x_reg_2 * p22N3_mul_cast;
  p22N3_mul_cast_1 <= p22N3_mul_mul_temp(27 DOWNTO 0);
  p22N3_mul_cast_2 <= p22N3_mul_cast_1(27 DOWNTO 14);
  N3_mul <= p22N3_mul_cast_2(12 DOWNTO 0) & '0';

  p19N2_mul_cast <= signed(resize(h1_reg, 15));
  p19N2_mul_mul_temp <= x_reg_1 * p19N2_mul_cast;
  p19N2_mul_cast_1 <= p19N2_mul_mul_temp(27 DOWNTO 0);
  p19N2_mul_cast_2 <= resize(p19N2_mul_cast_1(27 DOWNTO 16), 14);
  N2_mul <= p19N2_mul_cast_2(10 DOWNTO 0) & '0' & '0' & '0';

  p44N11_mul_add_cast <= resize(N1_mul, 18);
  p44N11_mul_add_cast_1 <= resize(N2_mul & '0' & '0' & '0', 18);
  p44N11_mul_add_temp <= p44N11_mul_add_cast + p44N11_mul_add_cast_1;
  p44N11_mul_cast <= resize(p44N11_mul_add_temp(17 DOWNTO 6), 14);
  N11_mul <= p44N11_mul_cast(10 DOWNTO 0) & '0' & '0' & '0';

  p45N12_mul_add_cast <= resize(N3_mul & '0' & '0', 17);
  p45N12_mul_add_cast_1 <= resize(N11_mul, 17);
  p45N12_mul_add_temp <= p45N12_mul_add_cast + p45N12_mul_add_cast_1;
  p45N12_mul_cast <= p45N12_mul_add_temp(16 DOWNTO 3);
  N12_mul <= p45N12_mul_cast(12 DOWNTO 0) & '0';

  p46N13_mul_add_cast <= resize(N4_mul & '0', 16);
  p46N13_mul_add_cast_1 <= resize(N12_mul, 16);
  p46N13_mul_add_temp <= p46N13_mul_add_cast + p46N13_mul_add_cast_1;
  N13_mul <= p46N13_mul_add_temp(14 DOWNTO 1);

  N14_mul <= N5_mul + N13_mul;

  N15_mul <= N6_mul + N14_mul;

  N16_mul <= N7_mul + N15_mul;

  p50N17_mul_add_cast <= resize(N8_mul, 16);
  p50N17_mul_add_cast_1 <= resize(N16_mul & '0', 16);
  p50N17_mul_add_temp <= p50N17_mul_add_cast + p50N17_mul_add_cast_1;
  N17_mul <= p50N17_mul_add_temp(14 DOWNTO 1);

  p51N18_mul_add_cast <= resize(N9_mul, 18);
  p51N18_mul_add_cast_1 <= resize(N17_mul & '0' & '0' & '0', 18);
  p51N18_mul_add_temp <= p51N18_mul_add_cast + p51N18_mul_add_cast_1;
  N18_mul <= p51N18_mul_add_temp(16 DOWNTO 3);

  p52N19_mul_add_cast <= resize(N10_mul, 21);
  p52N19_mul_add_cast_1 <= resize(N18_mul & '0' & '0' & '0' & '0' & '0' & '0', 21);
  p52N19_mul_add_temp <= p52N19_mul_add_cast + p52N19_mul_add_cast_1;
  N19_mul <= p52N19_mul_add_temp(19 DOWNTO 6);

  y <= std_logic_vector(N19_mul);

  ce_out <= clk_enable;

END rtl;

